/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BorradorPrograma;

import Plantillas.CalculoProductos2;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CalculoProductos extends javax.swing.JFrame {

    int i; float pacl,cam;
    public CalculoProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFProduc = new javax.swing.JTextField();
        jBAceptar = new javax.swing.JButton();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Paper Bow DEMO", 3, 30)); // NOI18N
        jLabel2.setText("Calculo de Productos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("UnicornFlakes", 0, 18)); // NOI18N
        jLabel1.setText("Numero de Productos a calcular:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jTFProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFProducActionPerformed(evt);
            }
        });
        getContentPane().add(jTFProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 220, 40));

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jBAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        jLFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/99.png"))); // NOI18N
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFProducActionPerformed
    
    }//GEN-LAST:event_jTFProducActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
         
        int n = Integer.parseInt(jTFProduc.getText());
         for(i=1;i<=n;i++)
           {
                CalculoProductos2 abrirmenu= new CalculoProductos2();
                 abrirmenu.setVisible(true);
                  dispose();
           }
         
         
    }//GEN-LAST:event_jBAceptarActionPerformed
void Pago(int acum){
          JOptionPane.showMessageDialog(null,"El total a pagar es: $"+acum);
           pacl=Float.parseFloat(JOptionPane.showInputDialog("Escriba la cantidad que pago el cliente: "));
           cam=pacl-acum;
           JOptionPane.showMessageDialog(null,"El total a regresar al cliente es: $"+cam);
         }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculoProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTFProduc;
    // End of variables declaration//GEN-END:variables
}
